all: 
	python2 ./create.py
	rm spiewnik.[^p]*
	rm all.[^p]*

clean:
	rm spiewnik.*
	rm toc.[^t]*
	rm all.*

remove:
	rm spiewnik.[^p]*
	rm toc.[^t^p]*
	rm all.[^p]*

random:
	python2 ./create.py random
	rm spiewnik.[^p]*
	rm all.[^p]*
